server:
  port: 9093

spring:
  application:
    name: order-service
  datasource:
          password: root
          url: jdbc:mysql://localhost:3306/shopping-cart
          username: root
  jpa:
          hibernate:
            ddl-auto: update

          properties:
            hibernate:
              dialect: org.hibernate.dialect.MySQL8Dialect
              format_sql: true
          show-sql: true
redis:
          server:
                host: 127.0.0.1
                port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true


